// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuOYTJCELmEQg8vuFHB-mPIw07KwUazE',
    appId: '1:209978110915:web:54b8ce655ab296c8978376',
    messagingSenderId: '209978110915',
    projectId: 'eco-friendly-products-store',
    authDomain: 'eco-friendly-products-store.firebaseapp.com',
    storageBucket: 'eco-friendly-products-store.firebasestorage.app',
    measurementId: 'G-MP6L0M8WDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FANnQesAHv9UvqWt1ayxGDA02YHlJdQ',
    appId: '1:209978110915:android:12ec0e6383417d46978376',
    messagingSenderId: '209978110915',
    projectId: 'eco-friendly-products-store',
    storageBucket: 'eco-friendly-products-store.firebasestorage.app',
  );

}